package io.dawn.budget.entity;

public enum ExpenseCategory {
    FOOD, HOUSING, UTILITIES, MEDICAL_HEALTH_CARE, INSURANCE, TRANSPORTATION, CLOTHING, HOUSEHOLD_SUPPLIES, PERSONAL,
    DEBT, ENTERTAINMENT, OTHER;

}
